# Generated by Django 3.2 on 2021-06-15 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_module_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('video_url', models.URLField()),
                ('can_view', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='course_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_types',
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default=1, upload_to='course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_type',
            field=models.CharField(choices=[('F', 'FREE'), ('M', 'MONTHLY'), ('Y', 'YEARLY')], default='FREE', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
